name: CD Backend (Azure)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: Backend
        run: npm ci

      - name: Zip backend
        run: |
          cd Backend
          zip -r ../backend.zip . -x "**/node_modules/**"

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3
        with:
          app-name: petitemaison-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip
